[package]
name = "polkadot-statement-table"
version = "0.8.28"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/tomaka/polkadot", branch = "extract-tx-protocol" }
primitives = { package = "polkadot-primitives", path = "../primitives" }
